### ISSUE TITLE
Add Llama 3

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#100]
release-by-blogpost
> https://ai.meta.com/blog/meta-llama-3-1/

Zuckerberg doubles down on "open source" 
> https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/

/edit Oh we have it already, the latest buzz is just because some cherrypicked parameters made it past GPT4 performance

**Comment by janchk** [comment]
This PR #101 probably related to the issue. Some changes happened since llama 3 revision.

**Comment by mdingemanse** [comment]
thank you for your contribution!
