### ISSUE TITLE
Table: skip sample .csv

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#15]
We want to have an empty sample .csv in /projects/ that people can use to add a new project, but that itself won't show up.

Two ways of going about this:
1. Hardcode `sample.csv` as a csv that will never be included
2. Check whether `project_name` = "" and exclude based on that

I prefer option 2 because it is cleaner / more flexible

**Comment by timjzee** [comment]
We now exclude project files without a project_name.
