### ISSUE TITLE
Generate single index.html

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#22]
Right now `table.html` is rendered and javascript is used to plug it into index.html on load. Advantage: we can edit the header and footer info separately from the generated table. Disadvantage: probably not being indexed optimally, so not great for SEO.

Goal: render a single index.html, while keeping the ability for us to edit the info above and below the table separately.

So: can we have a script combine template.html and table.html (in template.html, a `<div id="included-table"></div>` would determine where the table goes)?

**Comment by timjzee** [comment]
Pull request closes this issue
