### ISSUE TITLE
Consider moving from csv to yaml

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#24]
CSV is tricky to edit and we run into issues with separators (esp. ,) in some fields (e.g. notes); yaml is more human readable.

**Comment by timjzee** [comment]
I could make it so both .yaml files formatted like: 7be2e38742500cc80b7ed13adbfb0a4c13eee0a7 and .csv files are accepted. You can then decide what to do later.

**Comment by timjzee** [comment]
Closed by 514ea1330023af9060f277094a018fe130a4a396

**Comment by mdingemanse** [comment]
amazing work @timjzee, well done!
