### ISSUE TITLE
Nice to have: include data of last revision/render on github page

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#25]
The ACL anthology (built using Hugo) has this nice footer showing when the page was last rendered. Since our table is auto-generated, it would be great to mention the date of last rendering.

![image](https://github.com/liesenf/opening-up-chatgpt/assets/9883915/d39969c7-1b29-4a6f-ba3a-9362e229dc45)

(In case it's relevant, [here's how](https://github.com/acl-org/acl-anthology/blob/9714206771c01f9612d1db2024c5d559b752dfac/hugo/layouts/partials/footer.html#L14) ACL does it. But I suspect that's a hugo-specific implementation.)

**Comment by timjzee** [comment]
Works. Any changes before closing? @mdingemanse

**Comment by mdingemanse** [comment]
Perfect!
