### ISSUE TITLE
Nice to have: direct link to metadata source file in table

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#27]
We use the `title` attribute to show notes on hover, but this makes sense only on desktops. To make the notes more accessible, each row should probably also include a direct link to the source CSV. 

A good place for this link would be the right most cell of the secondary row (in grey like the other text in that row).

Additional benefit is that it provides a quick link for when folks want to contribute edits.

**Comment by mdingemanse** [comment]
How easy is this for you @timjzee? If you give me something like `<a href="" class="source-link">§<a>` in the rightmost cell of row-b I can style it.

**Comment by timjzee** [comment]
Works, but you may want to adjust styling, @mdingemanse ?

**Comment by mdingemanse** [comment]
Nice — and can we have the source filename as the `title` attribute of that link?

**Comment by timjzee** [comment]
Can be closed?
