### ISSUE TITLE
Explore ways to transclude yaml files

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#34]
The permalink generation method like the below looks very nice (good find @liesenf). However, it is tied to a particular commit, so it won't update. (This is where the hash comes from.)

https://github.com/opening-up-chatgpt/opening-up-chatgpt.github.io/blob/4dfeae8db12bdd00b8bc7a1c83405b82c99b0aa1/projects/BELLE.yaml#L3-L70

Any other methods available?

**Comment by mdingemanse** [comment]
I wonder if we can trigger a github action to the the updating for us: any time a yaml file is updated, regenerate permalinks to the code and update readme.md with the latest versoin.

**Comment by liesenf** [comment]
This would be GREAT

**Comment by mdingemanse** [comment]
closing as stale
