### ISSUE TITLE
change the title?

### ISSUE THREAD

**Issue by heaversm** [opening-up-chatgpt/opening-up-chatgpt.github.io#53]
This is a great resource. I had an incredibly difficult time finding it again in my search history because of the title, "Opening up ChatGPT" because I was looking for something that alluded to comparison of LLM models on their open-source characteristics.  Think you might improve discoverability by being more explicit there.

Thanks for the resource!

**Comment by mdingemanse** [comment]
Thank you! The repo title is a shortened version of the full paper title:

> Opening up ChatGPT: Tracking openness, transparency, and accountability in instruction-tuned text generators
> https://dl.acm.org/doi/10.1145/3571884.3604316

Do you mean the repo might also benefit from that longer title?
