### ISSUE TITLE
Make link to yaml source more prominent

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#57]
On mobile devices, hover won't work so the site doesn't adequately show the sheer number of evidence-based data points we have assembled. It is also hard to hit the § link at the end of a secondary row.

Proposal: link every model name to its yaml file, use `org` name to link to `project: link` (org doesn't need its own link, they have enough SEO juice anyway). What do you say @liesenf @timjzee ?

**Comment by timjzee** [comment]
What should happen to the § link?

**Comment by mdingemanse** [comment]
I think that could go then, if the model name would then be formatted like:
`<a href="/projects/file_name.yaml}" title="data: {yaml_file_name.yaml}">{project}</a>`

(I know I introduced the § myself in #27 :D )

**Comment by timjzee** [comment]
I couldn't say goodbye yet to our friend §. It now links to the org. Everything else is as you proposed. @mdingemanse
