### ISSUE TITLE
Update OpenChat

### ISSUE THREAD

**Issue by imoneoi** [opening-up-chatgpt/opening-up-chatgpt.github.io#75]
OpenChat paper is recently accepted by ICLR 2024 https://openreview.net/forum?id=AOJyfhWYHf

**Comment by mdingemanse** [comment]
Thank you, looking forward to update this data point. 

I note by the way that the paper talks of 'open-source' models where actually most of these are at best 'open weight' — nothing about the source of most of the tested models is actually open. 

![Screenshot_20240129-193549_Firefox](https://github.com/opening-up-chatgpt/opening-up-chatgpt.github.io/assets/9883915/94c29302-b301-43d2-8cc2-7515b80ef539)

**Comment by mdingemanse** [comment]
@imoneoi is there a canonical URL or a DOI? Openreview.net review forum IDs are not guaranteed to be durable links. (If the arxiv.org submission is updated with the accepted version and includes a note like 'accepted at ICLR', we would prefer that.)
