### ISSUE TITLE
add AllenAI's Olmo if they release an instruction tuned version

### ISSUE THREAD

**Issue by mdingemanse** [opening-up-chatgpt/opening-up-chatgpt.github.io#77]
https://blog.allenai.org/olmo-open-language-model-87ccfc95f580

**Comment by tieguy** [comment]
Possibly a dumb question, but why only if they release an instruction-tuned version?

**Comment by mdingemanse** [comment]
Because this repo tracks only those — too many base models for us to (also) track...

**Comment by mdingemanse** [comment]
Seems to have arrived: https://huggingface.co/allenai/OLMo-7B-Instruct
